language: generic
sudo: required
dist: trusty
before_install:
  - sudo apt-add-repository -y ppa:lttng/ppa
  - sudo apt-get update
  - sudo apt-get install -y python3-setuptools python-virtualenv python3-babeltrace babeltrace
install:
  - virtualenv --system-site-packages -p python3 .venv
  - . .venv/bin/activate
  - python3 setup.py install
script:
  - python3 setup.py test
  - LC_ALL=C python3 setup.py test
